[colors.primary]
background = "#001919"
foreground = "#ffffff"

[colors.cursor]
text = "#001919"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#001919"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#001919"
background = "#ffffff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#205f5f"
background = "#ffffff"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#001919"
red = "#76b2b2"
green = "#86b1b1"
yellow = "#90b7b7"
blue = "#96c0c0"
magenta = "#a7bebe"
cyan = "#8EAFAF"
white = "#F3F5F5"

[colors.bright]
black = "#205f5f"
red = "#afd5d5"
green = "#bdd6d6"
yellow = "#c7dcdc"
blue = "#cee3e3"
magenta = "#dbe5e5"
cyan = "#c3d6d6"
white = "#ffffff"

[colors.dim]
black = "#ffffff"
red = "#afd5d5"
green = "#bdd6d6"
yellow = "#c7dcdc"
blue = "#cee3e3"
magenta = "#dbe5e5"
cyan = "#c3d6d6"
white = "#205f5f"
