# Background and foreground colors
background = #001919
foreground = #ffffff

# Standard colors
palette = 0=#001919
palette = 1=#76b2b2
palette = 2=#86b1b1
palette = 3=#90b7b7
palette = 4=#96c0c0
palette = 5=#a7bebe
palette = 6=#8EAFAF
palette = 7=#F3F5F5

# Bright colors
palette = 8=#205f5f
palette = 9=#afd5d5
palette = 10=#bdd6d6
palette = 11=#c7dcdc
palette = 12=#cee3e3
palette = 13=#dbe5e5
palette = 14=#c3d6d6
palette = 15=#ffffff
