# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(205f5fee) rgba(205f5fee) 45deg
    col.inactive_border = rgba(205f5f55) rgba(205f5f55) 90deg
}
