background            #001919
foreground            #ffffff

# black
color0  #001919
color8  #205f5f

# red
color1  #76b2b2
color9  #afd5d5

# green
color2  #86b1b1
color10 #bdd6d6

# yellow
color3  #90b7b7
color11 #c7dcdc

# blue
color4  #96c0c0
color12 #cee3e3

# magenta
color5  #a7bebe
color13 #dbe5e5

#cyan
color6  #8EAFAF
color14 #c3d6d6

#white
color7  #F3F5F5
color15 #ffffff


